WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

FPS = 60

# Background Constants
BG_TOP_SCROLL_SPEED = 50
BG_BOTTOM_SCROLL_SPEED = 100
GROUND_HEIGHT = 113

# Bird Constants
GRAVITY = 30
JUMP_FORCE = 10
JUMP_ROT_ANGLE = 30
FALL_ROT_THRESHOLD = 15
ROT_SPEED = 200

# Pipe Constants
PIPE_GAP_MIN = WINDOW_HEIGHT // 5
PIPE_GAP_MAX = WINDOW_HEIGHT // 3
PIPE_HIT_TOP_TOLERANCE = 15
PIPE_HIT_BOTTOM_TOLERANCE = 15
PIPE_HORIZONTAL_GAP = WINDOW_WIDTH // 4
PIPE_MIN_HEIGHT = GROUND_HEIGHT + PIPE_GAP_MIN // 2
PIPE_MAX_HEIGHT = WINDOW_HEIGHT - PIPE_GAP_MAX - PIPE_MIN_HEIGHT
